name: SkyZero
version: 1.0-SNAPSHOT
main: ppeerapon.mc.skyzero.SkyZero
api-version: 1.16
authors: [ Ppeerapon ]
description: A Minecraft Plugin.
commands:
  Fly:
    usage: /<command>
    description: I belive I can fly.
  Hologram:
    usage: /<command> <text>
    description: Hologram is here.
  Kick:
    usage: /<command> <player>
    description: Kick some player.
  Path:
    usage: /<command>
    description: Make a path for you.
  Message:
    usage: /<command>
    aliases: [reply, msg]
    description: Private message.
  Menu:
    usage: /<command>
    description: Open GUI.
  Skull:
    usage: /<commmand>
    description: Get a skull.
  Banner:
    usage: /<commmand>
    description: Create a banner.
  Map:
    usage: /<commmand> <url>
    description: Set map image.
  Book:
    usage: /<command>
    description: Get a high quality book.
  Help:
    usage: /<command>
    description: Need some help ?
  Text:
    usage: /<command>
    description: Super Text.
  Broadcast:
    usage: /<command>
    description: Tell something to everyone.
  SetSkin:
    usage: /<command>
    description: Set your skin to someone else.
  GUI:
    usage: /<command>
    description: Open dynamic gui.
  Rank:
    usage: /<command> <player> <rank>
    description: Change someone rank.

